# Configuration for flavours
# https://github.com/Misterio77/flavours
#
# Example config and default values
#
# [[item]]
# file = '~/.config/example' (file to inject to, supports tilde and env var expansion. required)
# template = 'example' (template to use. required)
# subtemplate = 'default' (subtemplate to use)
# rewrite = false (should we rewrite the entire file?)
# start = '# Start flavours' (if not rewriting, where to start replacing)
# end = '# End flavours' (if not rewriting, where to stop replacing)
# hook = '' (command to execute after injecting)
#
# Example for i3
#
# [[item]]
# file = '~/.config/i3/config'
# template = 'i3'
# subtemplate = 'colors'
# hook = 'i3-msg reload'
# rewrite = false

[[item]]
file = '~/.config/alacritty/alacritty.yml'
template = 'alacritty'
rewrite = true

[[item]]
file = '~/.zsh_colors'
template = 'shell'
rewrite = true

[[item]]
file = '~/.config/zathura/zathurarc'
template = 'zathura'
rewrite = true

[[item]]
file = '~/.config/nvim/colors/base16.vim'
template = 'vim'
rewrite = false
start= '" Start flavours'
end = '" End flavours'

[[item]]
file = '~/.config/sway/colorscheme'
template = "sway"
subtemplate = "colors"
hook = "swaymsg reload"
light = false
rewrite = true

[[item]]
file = '~/.config/mako/config'
template = "mako"
hook = "makoctl reload"
light = false
rewrite = true

[[item]]
file = '~/.themes/FlatColor/colors2'
template = 'gtk-flatcolor'
subtemplate = 'gtk-2'
rewrite = true

[[item]]
file = '~/.themes/FlatColor/colors3'
template = 'gtk-flatcolor'
subtemplate = 'gtk-3'
rewrite = true
hook = 'killall -HUP xsettingsd'

[[item]]
file = '~/.config/qutebrowser/config.py'
template = 'qutebrowser'
subtemplate = 'minimal'
rewrite = false
start= '# Start flavours'
end = '# End flavours'
hook = 'pgrep -x qutebrowser && qutebrowser :config-source'

# [[item]]
# file = '~/.Xresources'
# template = 'xresources'
# rewrite = false
# start= '/* Start flavours */'
# end = '/* End flavours */'
# hook = 'xrdb -override ~/.Xresources'
